framework:
    rate_limiter:
        test_submission:
            policy: 'fixed_window'
            limit: 31
            interval: '1 hour'

        test_view:
            policy: 'fixed_window'
            limit: 100
            interval: '1 minute'