<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5unA8SdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5unA8Sd' shared service.
     *
     * @return \App\Repository\ReponsesScoreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\teste\\ReponsesScoreController::index()": the $reponsesScoreRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ReponsesScoreRepository".');
    }
}
