<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CIopn1RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cIopn1R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rdvRepo' => ['privates', 'App\\Repository\\RendezVouRepository', 'getRendezVouRepositoryService', true],
        ], [
            'em' => '?',
            'rdvRepo' => 'App\\Repository\\RendezVouRepository',
        ]);

        if (isset($container->privates['.service_locator.cIopn1R'])) {
            return $container->privates['.service_locator.cIopn1R'];
        }

        return $container->privates['.service_locator.cIopn1R'] = $instance;
    }
}
