<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIG8MmBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bIG8MmB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bIG8MmB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reponsesScoreRepository' => ['privates', '.errored.5unA8Sd', NULL, 'Cannot determine controller argument for "App\\Controller\\teste\\ReponsesScoreController::index()": the $reponsesScoreRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ReponsesScoreRepository".'],
        ], [
            'reponsesScoreRepository' => '?',
        ]);
    }
}
