<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K_CvEiNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k.CvEiN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rdv' => ['privates', '.errored..service_locator.k.CvEiN.App\\Entity\\RendezVou', NULL, 'Cannot autowire service ".service_locator.k.CvEiN": it needs an instance of "App\\Entity\\RendezVou" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'rdv' => 'App\\Entity\\RendezVou',
        ]);

        if (isset($container->privates['.service_locator.k.CvEiN'])) {
            return $container->privates['.service_locator.k.CvEiN'];
        }

        return $container->privates['.service_locator.k.CvEiN'] = $instance;
    }
}
