<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Aqkl7Z9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aqkl7Z9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fiche' => ['privates', '.errored..service_locator.aqkl7Z9.App\\Entity\\FicheConsultation', NULL, 'Cannot autowire service ".service_locator.aqkl7Z9": it needs an instance of "App\\Entity\\FicheConsultation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'fiche' => 'App\\Entity\\FicheConsultation',
        ]);

        if (isset($container->privates['.service_locator.aqkl7Z9'])) {
            return $container->privates['.service_locator.aqkl7Z9'];
        }

        return $container->privates['.service_locator.aqkl7Z9'] = $instance;
    }
}
