<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IUU1deLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iUU1deL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iUU1deL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'test' => ['privates', '.errored..service_locator.iUU1deL.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.iUU1deL": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
            'testViewLimiter' => ['privates', 'limiter.test_view', 'getLimiter_TestViewService', true],
        ], [
            'test' => 'App\\Entity\\Test',
            'testViewLimiter' => '?',
        ]);
    }
}
