<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NUmlGk9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nUmlGk9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nUmlGk9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'test' => ['privates', '.errored..service_locator.nUmlGk9.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.nUmlGk9": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pdfService' => 'App\\Service\\PdfService',
            'test' => 'App\\Entity\\Test',
        ]);
    }
}
