<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FSOv7EiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FSOv7Ei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gemini' => ['privates', 'App\\Service\\GeminiService', 'getGeminiServiceService', true],
            'scoringService' => ['privates', 'App\\Service\\ScoringService', 'getScoringServiceService', true],
            'test' => ['privates', '.errored..service_locator.FSOv7Ei.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.FSOv7Ei": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
            'testSubmissionLimiter' => ['privates', 'limiter.test_submission', 'getLimiter_TestSubmissionService', true],
        ], [
            'em' => '?',
            'gemini' => 'App\\Service\\GeminiService',
            'scoringService' => 'App\\Service\\ScoringService',
            'test' => 'App\\Entity\\Test',
            'testSubmissionLimiter' => '?',
        ]);

        if (isset($container->privates['.service_locator.FSOv7Ei'])) {
            return $container->privates['.service_locator.FSOv7Ei'];
        }

        return $container->privates['.service_locator.FSOv7Ei'] = $instance;
    }
}
