<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T0sjJJJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T0sjJJJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'snappy' => ['services', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
        ], [
            'em' => '?',
            'snappy' => 'Knp\\Snappy\\Pdf',
        ]);

        if (isset($container->privates['.service_locator.T0sjJJJ'])) {
            return $container->privates['.service_locator.T0sjJJJ'];
        }

        return $container->privates['.service_locator.T0sjJJJ'] = $instance;
    }
}
