<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8mzfGKzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8mzfGKz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticator' => ['privates', 'security.authenticator.form_login.main', 'getSecurity_Authenticator_FormLogin_MainService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
        ], [
            'authenticator' => 'Symfony\\Component\\Security\\Http\\Authenticator\\AbstractLoginFormAuthenticator',
            'em' => '?',
            'userAuthenticator' => '?',
        ]);

        if (isset($container->privates['.service_locator.8mzfGKz'])) {
            return $container->privates['.service_locator.8mzfGKz'];
        }

        return $container->privates['.service_locator.8mzfGKz'] = $instance;
    }
}
