<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlerteCritiqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DTsqGsq.App\Entity\AlerteCritique' shared service.
     *
     * @return \App\Entity\AlerteCritique
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DTsqGsq": it needs an instance of "App\\Entity\\AlerteCritique" but this type has been excluded in "config/services.yaml".');
    }
}
