<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\AdminControllerUser' shared autowired service.
     *
     * @return \App\Controller\user\AdminControllerUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'user'.\DIRECTORY_SEPARATOR.'AdminControllerUser.php';

        $container->services['App\\Controller\\user\\AdminControllerUser'] = $instance = new \App\Controller\user\AdminControllerUser();

        $instance->setContainer(($container->privates['.service_locator.rz2KodV'] ?? $container->load('get_ServiceLocator_Rz2KodVService'))->withContext('App\\Controller\\user\\AdminControllerUser', $container));

        return $instance;
    }
}
