<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\teste\FrontTestController' shared autowired service.
     *
     * @return \App\Controller\teste\FrontTestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'teste'.\DIRECTORY_SEPARATOR.'FrontTestController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AlerteService.php';

        $container->services['App\\Controller\\teste\\FrontTestController'] = $instance = new \App\Controller\teste\FrontTestController(new \App\Service\AlerteService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('ADMIN_EMAIL')));

        $instance->setContainer(($container->privates['.service_locator.rz2KodV'] ?? $container->load('get_ServiceLocator_Rz2KodVService'))->withContext('App\\Controller\\teste\\FrontTestController', $container));

        return $instance;
    }
}
