<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheConsultationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aqkl7Z9.App\Entity\FicheConsultation' shared service.
     *
     * @return \App\Entity\FicheConsultation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aqkl7Z9": it needs an instance of "App\\Entity\\FicheConsultation" but this type has been excluded in "config/services.yaml".');
    }
}
