<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaceppServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FaceppService' shared autowired service.
     *
     * @return \App\Service\FaceppService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FaceppService.php';

        return $container->privates['App\\Service\\FaceppService'] = new \App\Service\FaceppService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('FACEPP_API_KEY'), $container->getEnv('FACEPP_API_SECRET'));
    }
}
