<?php

namespace ContainerI9rlItm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponsesScoreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JOmh5yw.App\Entity\ReponsesScore' shared service.
     *
     * @return \App\Entity\ReponsesScore
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JOmh5yw": it needs an instance of "App\\Entity\\ReponsesScore" but this type has been excluded in "config/services.yaml".');
    }
}
