<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AALPpBdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AALPpBd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dompdf' => ['services', 'dompdf', 'getDompdfService', true],
            'ficheRepo' => ['privates', 'App\\Repository\\FicheConsultationRepository', 'getFicheConsultationRepositoryService', true],
        ], [
            'dompdf' => '?',
            'ficheRepo' => 'App\\Repository\\FicheConsultationRepository',
        ]);

        if (isset($container->privates['.service_locator.AALPpBd'])) {
            return $container->privates['.service_locator.AALPpBd'];
        }

        return $container->privates['.service_locator.AALPpBd'] = $instance;
    }
}
