<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SBYDYZLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SBYDYZL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponsesScore' => ['privates', '.errored..service_locator.SBYDYZL.App\\Entity\\ReponsesScore', NULL, 'Cannot autowire service ".service_locator.SBYDYZL": it needs an instance of "App\\Entity\\ReponsesScore" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reponsesScore' => 'App\\Entity\\ReponsesScore',
        ]);

        if (isset($container->privates['.service_locator.SBYDYZL'])) {
            return $container->privates['.service_locator.SBYDYZL'];
        }

        return $container->privates['.service_locator.SBYDYZL'] = $instance;
    }
}
