<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JOmh5ywService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JOmh5yw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JOmh5yw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reponsesScore' => ['privates', '.errored..service_locator.JOmh5yw.App\\Entity\\ReponsesScore', NULL, 'Cannot autowire service ".service_locator.JOmh5yw": it needs an instance of "App\\Entity\\ReponsesScore" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reponsesScore' => 'App\\Entity\\ReponsesScore',
        ]);
    }
}
