<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VvgQ7atService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vvgQ7at' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rdvRepo' => ['privates', 'App\\Repository\\RendezVouRepository', 'getRendezVouRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'em' => '?',
            'rdvRepo' => 'App\\Repository\\RendezVouRepository',
            'validator' => '?',
        ]);

        if (isset($container->privates['.service_locator.vvgQ7at'])) {
            return $container->privates['.service_locator.vvgQ7at'];
        }

        return $container->privates['.service_locator.vvgQ7at'] = $instance;
    }
}
