<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8l4yBX2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8l4yBX2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gcal' => ['privates', 'App\\Service\\GoogleCalendarService', 'getGoogleCalendarServiceService', true],
        ], [
            'em' => '?',
            'gcal' => 'App\\Service\\GoogleCalendarService',
        ]);

        if (isset($container->privates['.service_locator.8l4yBX2'])) {
            return $container->privates['.service_locator.8l4yBX2'];
        }

        return $container->privates['.service_locator.8l4yBX2'] = $instance;
    }
}
