<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LpzeClbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lpzeClb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ficheRepo' => ['privates', 'App\\Repository\\FicheConsultationRepository', 'getFicheConsultationRepositoryService', true],
            'notifRepo' => ['privates', 'App\\Repository\\NotificationrendezVouRepository', 'getNotificationrendezVouRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'rdvRepo' => ['privates', 'App\\Repository\\RendezVouRepository', 'getRendezVouRepositoryService', true],
        ], [
            'em' => '?',
            'ficheRepo' => 'App\\Repository\\FicheConsultationRepository',
            'notifRepo' => 'App\\Repository\\NotificationrendezVouRepository',
            'paginator' => '?',
            'rdvRepo' => 'App\\Repository\\RendezVouRepository',
        ]);

        if (isset($container->privates['.service_locator.lpzeClb'])) {
            return $container->privates['.service_locator.lpzeClb'];
        }

        return $container->privates['.service_locator.lpzeClb'] = $instance;
    }
}
