<?php

namespace ContainerKpxrNXP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BorKgzkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BorKgzk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BorKgzk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'facepp' => ['privates', 'App\\Service\\FaceppService', 'getFaceppServiceService', true],
        ], [
            'facepp' => 'App\\Service\\FaceppService',
        ]);
    }
}
