<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'alertesSuicides' => [parent::class, 'alertesSuicides', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'googleCalendarToken' => [parent::class, 'googleCalendarToken', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null, 16],
        "\0".parent::class."\0".'participation' => [parent::class, 'participation', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phone_number' => [parent::class, 'phone_number', null, 16],
        "\0".parent::class."\0".'profile_photo' => [parent::class, 'profile_photo', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'alertesSuicides' => [parent::class, 'alertesSuicides', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'googleCalendarToken' => [parent::class, 'googleCalendarToken', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'notifications' => [parent::class, 'notifications', null, 16],
        'participation' => [parent::class, 'participation', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phone_number' => [parent::class, 'phone_number', null, 16],
        'profile_photo' => [parent::class, 'profile_photo', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
