<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RendezVou extends \App\Entity\RendezVou implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateRendezVous' => [parent::class, 'dateRendezVous', null, 16],
        "\0".parent::class."\0".'google_event_id' => [parent::class, 'google_event_id', null, 16],
        "\0".parent::class."\0".'heureDebut' => [parent::class, 'heureDebut', null, 16],
        "\0".parent::class."\0".'heureFin' => [parent::class, 'heureFin', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'medecin' => [parent::class, 'medecin', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'type_seance' => [parent::class, 'type_seance', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'dateRendezVous' => [parent::class, 'dateRendezVous', null, 16],
        'google_event_id' => [parent::class, 'google_event_id', null, 16],
        'heureDebut' => [parent::class, 'heureDebut', null, 16],
        'heureFin' => [parent::class, 'heureFin', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'medecin' => [parent::class, 'medecin', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'type_seance' => [parent::class, 'type_seance', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
