<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'creator_id' => [parent::class, 'creator_id', null, 16],
        "\0".parent::class."\0".'creator_type' => [parent::class, 'creator_type', null, 16],
        "\0".parent::class."\0".'event_date' => [parent::class, 'event_date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'link' => [parent::class, 'link', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'max_participants' => [parent::class, 'max_participants', null, 16],
        "\0".parent::class."\0".'participation' => [parent::class, 'participation', null, 16],
        "\0".parent::class."\0".'planifications' => [parent::class, 'planifications', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'creator_id' => [parent::class, 'creator_id', null, 16],
        'creator_type' => [parent::class, 'creator_type', null, 16],
        'event_date' => [parent::class, 'event_date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'link' => [parent::class, 'link', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'max_participants' => [parent::class, 'max_participants', null, 16],
        'participation' => [parent::class, 'participation', null, 16],
        'planifications' => [parent::class, 'planifications', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'title' => [parent::class, 'title', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
