parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Symfony\Component\RateLimiter\RateLimiterFactory $testSubmissionLimiter: '@limiter.test_submission'
            Symfony\Component\RateLimiter\RateLimiterFactory $testViewLimiter: '@limiter.test_view'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GeminiService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\FaceppService:
        arguments:
            $faceppApiKey:    '%env(FACEPP_API_KEY)%'
            $faceppApiSecret: '%env(FACEPP_API_SECRET)%'

    App\Service\PdfService:
        arguments:
            $projectDir: '%kernel.project_dir%'