<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKpxrNXP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKpxrNXP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKpxrNXP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKpxrNXP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKpxrNXP\App_KernelDevDebugContainer([
    'container.build_hash' => 'KpxrNXP',
    'container.build_id' => '7f20c4da',
    'container.build_time' => 1777729720,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKpxrNXP');
